### ISSUE TITLE
TASK: Design API

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/XbSymbolDatabase#10]
To be able to use this XbSymbolDatabase in Cxbx-Reloaded (and possible other projects, like via an IDA Pro plugin), we'll (obviously) be needing an API to access it's functionality.

Things that this library should be able to do :
* query the library for it's version & capabilities
* register symbol-table database(s) [ this might not be needed until #8 is decided upon ]
* start a scanning session, returning a handle
* scan a memory-range for symbols (internally adding the detected symbols to the session handle)
* retrieve the detected symbols in a session
* closing a scanning sessions, freeing all allocated resources

This API must be implemented with thread-safety in mind.
API signatures must be designed such, that future updates to the library could be added without breaking the interface.

The API that will be doing the actual scanning, must be able to be updated in the future, so it might be wise to give it only one argument : a structure pointer that passes in all arguments.
This way, the structure can be changed in the future, without breaking the BAPI.

Things that should go into the scanning struct:
* a struct version
* scanning flags (or a reserved DWORD to put those in once we need them)
* an indication of the range / ranges that should be scanned
  * per range: it's size in bytes, a pointer to it's data, and it's base-address in virtual-memory

Please discuss further below

**Comment by RadWolfie** [comment]
I think it should only handle one at a time, not multiple at a time. Unless that's what you are saying.

The goal for this current library project is to provide a global variable with a symbol list since it is only needed once for time being. Later on, we can create API to do individual symbol list provided by third-party project.

**Comment by RadWolfie** [comment]
Let's consider session API to be a 2nd edition once we have things done for Cxbx-Reloaded's requirement.

Consider this task as 2.2 milestone?

**Comment by PatrickvL** [comment]
Sure, it's all still in its infancy here.

I had my designer hat on when I write the above ;)

**Comment by JayFoxRox** [comment]
Since May 2018 the header has changed; It looks much more like an API now.
It's also being used by at least 2 users (https://github.com/Cxbx-Reloaded/Cxbx-Reloaded and https://github.com/Cxbx-Reloaded/XbSymbolCacheGenTest)

Some features mentioned here, still haven't been implemented: "start a scanning session, returning a handle" for example.
However, I think it's best to review this issue, and create separate issue for each required feature which isn't implemented yet. Then close this issue as the scope isn't well defined.

**Comment by RadWolfie** [comment]
This issue is more or less introduce a "class" method for v2.0 edition to allow run multiple xbe scans in different thread.

I don't have the time to do this process as I have other higher priority to fix. Once those fixes are done and if this work haven't started. Then I will start work on it.

**Comment by RadWolfie** [comment]
Due to XbSymbolUnitTest need variable symbols register, I have determine to put this on highest priority after pull request #66 and JVS. Then registering symbols will be easier for me to do without adding extra parameters over time.

**Comment by RadWolfie** [comment]
Pull request #10, stage 1, has the new APIs except have not transfer the old APIs into new APIs. Which will take time to develop for other projects, like my projects, to use the new APIs.

Once other projects are ready for second stage, final. All of the old APIs will be move into new APIs.
