### ISSUE TITLE
TASK: Create symbol address list

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/XbSymbolDatabase#2]
We need to create a generated list for each symbol, not each revision, somehow. Either macro or existing structure method.

Then we can use it in Cxbx-Reloaded project to make references for patch and trampoline to avoid workaround we have at the moment.

**Comment by LukeUsher** [comment]
The list generation and HLE Cache file generation can remain in Cxbx-Reloaded, as they are function specific.

I was thinking that the Symbol Scanning engine would remain in this project, outside of Cxbx-Reloaded, so that it could be called in this manner

Cxbx-Reloaded code:
```C++
std::map<std::string, xbaddr> g_SymbolAddresses;
void SymbolCallback(char* symbolName, xbaddr symbolAddress) {
  g_SymbolAddresses[symbolName] = symbolAddress;
}

XbSymbolScan(SymbolCallback);  // Call into this library
CxbxApplyPatches(); // Iterate through g_SymbolAddresses & resolve patches 
```

And everything else would remain in this project.
The ScanForXboxSymbols function would be part of this library and simply take a function pointer as input, and call it for every symbol found.

That way, the actual method of using the symbols is generic, and the application that uses this library can make all decisions on how to store or use the data returned.

**Comment by RadWolfie** [comment]
You finally found the best solution! I'm glad you thought about this before I lose my hair. 😉

**Comment by LukeUsher** [comment]
I'll be doing some work on Cxbx-Reloaded this weekend to decouple scanning and patching, so HLEIntercept/HLEDatabase will be renamed to SymbolDatabase and SymbolScan (so they can easily be removed later, once this project is mature) and there will be new function files for HLEPatch. 

That way, the symbol scanning and patching will become entirely separate. Sorry it took so long to get here!

**Comment by PatrickvL** [comment]
I'm afraid one thing is overlooked : the fact that symbol scanning is using XREF's to 'harden' searches.

An XREF is a pre-defined enumeration, that appears in a few forms : 
* as an ID for an OOVPA (registered in the XREF table once an OOVPA is found)
* as derived XREF's (currently hard-coded from a select few D3D OOVPA) 
* as cross-checked XREF's (XREF's which have to be found already, and which have to match the potential hit)

Once symbol scanning is completed, it's important to not only return the located OOVPA-based symbol locations, but also include all XREF symbol address. How's that going to play together with the idea of a symbol-callback? Call it afterwards for all XREF's? But by what name? Please discuss...

**Comment by LukeUsher** [comment]
That's not a problem, the hardening of the scanning using XREFs should remain in this library, as it is part of the scanning code itself and required for accurate symbol location.

The callback should be called for every single found, both XREF and not, so that the calling program can do whatever it likes with this information, but it shouldn't be necessary for the calling program to know anything about OOVPA or how scanning works internally, so it can switched out for other engines too

**Comment by PatrickvL** [comment]
Sure, I already suggested to do a symbol-callback on each detected XREF too, but again : by what name?

**Comment by RadWolfie** [comment]
Use the existing XREF enum from the library with by global variable which is XRefDataBase.

It will give you direct address after scanning is done. Unless you had manually input the address for the scan to do. In my opinion shouldn't do that.

**Comment by RadWolfie** [comment]
Also closing in favor new proposal in #3 to have external project to store it.
