### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by JayFoxRox** [Cxbx-Reloaded/XbSymbolDatabase#72]
XbSymbolDatabase should be relicensed to CC0 / BSD / MIT or something similar.

It's currently GPL, but that has a couple of drawbacks:

- Some tools, such as IDA Pro are not GPL and we couldn't legally make plugins for that.
- Most appstores don't allow Open-Source (so we need abilities to dual-license), so our own tools / debuggers for smartphones would possibly be impossible to release in the future.
- On Xbox, there's no dynamic linker, so even LGPL wouldn't be too helpful.

So while it's good to force users to provide code open-source, it's also preventing some use-cases or makes distribution more cumbersome.

I think it's bad for this library to force open-source anyway, as it's largely incompatible with its use cases. I can't think of a bad context either, where a non-open-source license would damage this project.

**Comment by RadWolfie** [comment]
Since not all contributors were carried over from Cxbx-Reloaded to XbSymbolDatabase. I looked through the history in "HLEDatabase" folder. These are the contributors that I know of did the work. However, I'm not sure if their original work still exist (during the rework process).

* caustiks (which username below?)
* blueshogun96
* jarupxx
* RadWolfie
* PatrickvL
* LukeUsher
* x1nixmzeng
* jackchentwkh
* anita999
* darrena092
* phire
* Echelon9
* dstien

Couple of users I did not included since they only did a manual add existing OOVPA to specific XDK version. Once we do have better information gathered from github's data. We'll need their approval for relicense as well.

**Comment by RadWolfie** [comment]
I am fine with either MIT or BSD 2 clause.

@LukeUsher replied to @JayFoxRox request for re-license.
> I’m all for BSD recently
> 2 clause I guess

**Comment by RadWolfie** [comment]
Both @JayFoxRox and @LukeUsher concluded the OOVPA signatures data are just data as they do not apply to code licensing.

While I agree with them, there are such thing for database licensing. For example: https://opendatacommons.org/licenses/odbl/

I don't think there will be an issue with re-license though.


Until we have all 5 has agree for re-license, we can't do anything yet.
[ ] Caustiks (founder of OOVPA structure)
[ ] @PatrickvL
[ ] @LukeUsher
[ ] @jarupxx
[ ] @RadWolfie

As they are the one who did scan process work.

**Comment by jarupxx** [comment]
I agree to re-license. MIT or BSD 2 clause is good I think.

**Comment by PatrickvL** [comment]
Whatever license is fine for me too

**Comment by caustik** [comment]
I agree

**Comment by RadWolfie** [comment]
Turns out I had not add @mborgerson to the list since he sent a pull request after this ticket. He is the one who made the cli tool which currently has no license to its header.
