### ISSUE TITLE
IDEA: Split actual OOVPA database from library itself

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/XbSymbolDatabase#8]
### Rationale :

The OOVPA database contained within this project is oriented specifically towards Xbox XDK symbols.
As it stands right now, this database is compiled into the binary, creating a hard binding between the scanning code and this database.

### Idea :

This project could be refactored a little into a general purpose symbol scanning library that could be applied in any project (something that to my knowledge is unique in the world - at least I haven't found any existing one yet).

### Steps :

For this, the following tasks would need to be done:
* Split this project into two :
  1.  the actual scanning library, offered as a .DLL under windows, or a .so under Linux
  2. the current Xbox XDK symbol database, as a binary that can be offered to the scanning library via some form of registration API
* Add and implement a symbol-table-registration API to the scanning library
* Design the registration API such, that it's signature doesn't need to change when new symbol-table formats are registered
* Symbol table formats that could be considered :
  * OOVPA
  * Dxbx PatternTrie
  * IDA Pro flirt files
  * .map files
  * .pdb files

Please discuss below

**Comment by RadWolfie** [comment]
In my opinion, it's best to provide a binary .lib extension and header file for accessibility to internal list and scanning functions. This should be more than enough for any xbox project to include directly into their own project without need to build a .DLL or .so binary file.

Plus XbSymbolDatabase library is very small, smaller than necessary to have a .DLL/.so file to be compile into.

If someone want to compile as .DLL/.so file extension, then more work is require to keep compatibility between windows and linux/mac. My suggestion is to create a separate project to include this XbSymbolDatabase library into .DLL for windows and another separate project for linux.

I for one, am not willing to do this task since I an 99% Windows user. (1% is just to see what's new for desktop version then lose interest fast.)

**Comment by jarupxx** [comment]
In my opinion on Symbol table formats.
Dxbx PatternTrie is better for import with external database, It's a very good choice.
OOVPA is readable format, but it will not be suitable for import external databases.
Perhaps IDA Pro is limited start pattern of 32 byte, will be occurs collisions in the database.

**Comment by PatrickvL** [comment]
The Dxbx pattern trie is a binary structure, compiled from text files. The same could be done for OOVPA's : compile them into a binary format. This would require a compilation step, and a description of the binary OOVPA storage format.

**Comment by jarupxx** [comment]
Oh, I mean that text files. I think that raw text files are better for general purpose symbol scanning library who prepared databases.

**Comment by RadWolfie** [comment]
I'll make it clearer for you guys.

XbSymbolDatabase is compiled into binary .lib file format, then Cxbx-R use the header and library files provided by XbSymbolDatabase straightforward.

XbSymbolDatabase `source code` --> compiled library `header + binary code` --> Program (either integrate, or create a plugin via .DLL/.so) `binary code`

When you compile XbSymbolDatabase, OOVPAs are not directly accessible. Hence the reason of using declared functions in header file for scanning purpose built-in.

If really want access to OOVPAs directly, then perform some includes requirement from OOVPADatabase folder. That's it.

**Comment by RadWolfie** [comment]
Closing since there's no interest to enable support for different binary formats to scan from this project. Beside, it never was the goal of this project either.
